"""Make slot_id non-nullable in bookings

Revision ID: 062e0396fb47
Revises: ecff44552dd2
Create Date: 2025-08-29 13:34:55.691360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062e0396fb47'
down_revision: Union[str, None] = 'ecff44552dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'slot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
