"""Add price column and __table_args__

Revision ID: 766e00cd4bb1
Revises: bbfbd22cfb39
Create Date: 2025-08-26 18:13:27.283389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766e00cd4bb1'
down_revision: Union[str, None] = 'bbfbd22cfb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'price')
    # ### end Alembic commands ###
