"""Add slot booking relationships in users table

Revision ID: bbfbd22cfb39
Revises: fcf768bb9fa5
Create Date: 2025-08-26 15:44:05.988653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfbd22cfb39'
down_revision: Union[str, None] = 'fcf768bb9fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
