"""make coach profile fields nullable

Revision ID: cd14fb4936db
Revises: 9796e07ce903
Create Date: 2025-08-19 12:32:18.974033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd14fb4936db'
down_revision: Union[str, None] = '9796e07ce903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qualifications', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charges_per_slot', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('availability_status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('coach_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coach_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('coach_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
