"""Add psych_tests module related tables

Revision ID: cf908fe22915
Revises: 062e0396fb47
Create Date: 2025-09-01 16:25:59.730053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf908fe22915'
down_revision: Union[str, None] = '062e0396fb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psych_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psych_tests_id'), 'psych_tests', ['id'], unique=False)
    op.create_table('psych_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['psych_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psych_questions_id'), 'psych_questions', ['id'], unique=False)
    op.create_table('psych_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['psych_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psych_options_id'), 'psych_options', ['id'], unique=False)
    op.create_table('psych_user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['psych_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['psych_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['psych_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psych_user_responses_id'), 'psych_user_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psych_user_responses_id'), table_name='psych_user_responses')
    op.drop_table('psych_user_responses')
    op.drop_index(op.f('ix_psych_options_id'), table_name='psych_options')
    op.drop_table('psych_options')
    op.drop_index(op.f('ix_psych_questions_id'), table_name='psych_questions')
    op.drop_table('psych_questions')
    op.drop_index(op.f('ix_psych_tests_id'), table_name='psych_tests')
    op.drop_table('psych_tests')
    # ### end Alembic commands ###
