"""Add mood while journal creation

Revision ID: e574646d44f4
Revises: cf908fe22915
Create Date: 2025-09-05 17:26:28.156398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e574646d44f4'
down_revision: Union[str, None] = 'cf908fe22915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('mood', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'mood')
    # ### end Alembic commands ###
